spring:
  datasource:
    url: jdbc:h2:mem:maindb
  sql:
    init:
      mode: always
  liquibase:
    enabled: true
    change-log: classpath:db.changelog/db.changelog-master.yml
  h2:
    console:
      enabled: true