spring:
  messages:
    baseName: messages
    encoding: UTF-8
    fallbackToSystemLocale: false

application:
  rightAnswersCountToPass: 3
  locale: ru-Ru
  fileNameByLocaleTag:
    ru-RU: questions_ru.csv
    en-US: questions.csv
